site_name: pyCamillaDSP
repo_url: https://github.com/HEnquist/pycamilladsp

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - client.md
  - general.md
  - status.md
  - config.md
  - volume.md
  - mute.md
  - levels.md
  - rate.md
  - settings.md
  - versions.md